[package]
name = "comp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antlr-rust = "0.3.0-beta"
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
codespan-reporting = "0.11.1"
