[package]
name = "comp_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
llvm_ir = { path = "../llvm_ir" }
mips_ir = { path = "../mips_ir" }

[dependencies.antlr-rust]
git = "https://github.com/jonatcln/antlr4rust.git"
rev = "0836c81f747b990bcfb97bb61970be0d2d6b5170"
