name: Rust

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo dependencies & build files
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: ./.ci/llvm
        key: llvm-15
    - name: Cache MARS
      id: cache-mars
      uses: actions/cache@v3
      with:
        path: ./.ci/mars
        key: Mars4_5
    - name: Format check
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy --no-deps --all -- -A unused -D warnings
    - name: Build
      run: cargo build --all --verbose
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15"
        directory: ./.ci/llvm
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: Install MARS
      if: ${{ !steps.cache-mars.outputs.cache-hit }}
      run: |
        wget https://github.com/dpetersanderson/MARS/releases/download/v.4.5.1/Mars4_5.jar \
          -O ./.ci/mars/Mars4_5.jar
    - name: Run tests
      run: cargo test --all --verbose
      env:
        MARS_BIN: ../.ci/mars.sh
