name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          ./llvm
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-llvm-15
    - name: Format check
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy --no-deps --all -- -Dwarnings
    - name: Build
      run: cargo build --all --verbose
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15"
        cached: ${{ steps.cache.outputs.cache-hit }}
    - name: Run tests
      run: cargo test --all --verbose
